apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:  # Correct indentation here
      - name: backend
        image: rafaykhan1/backend-image:latest  # Ensure this image is pushed to Docker Hub
        ports:
        - containerPort: 5000
        env:
        - name: SECRET_KEY
          value: "rafay"
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: "/secrets/gcp-key.json"
        volumeMounts:
        - name: gcp-key-volume
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-key-secret  # Ensure the secret exists in Kubernetes